### ISSUE TITLE
PropTypes is referenced in the react package, breaks for react >= 16.0

### ISSUE THREAD

**Issue by karmajunkie** [Personare/react-freshdesk-widget#9]
**Overview:**
PropTypes was broken out of react several versions back. It should now be included via the `prop-types` package.

**Use case:**
react >= 16.0 breaks this package

**Browsers:**
all of them

**Related issues:**

**Suggest a fix:**
Will submit a PR

**Comment by ceasbz** [comment]
Hello @karmajunkie, 

Thank you for contribute with this package \o/
